### ISSUE TITLE
Rating star display

### ISSUE THREAD

**Issue by Irinashl** [senlin/multilingual-comments-wpml#1]
Hi Pieter,
it would be very nice to display the rating stars on the translation page.
[Parent page](https://ibb.co/RC7V82n)
[Child page](https://ibb.co/dPj6RDB)
https://perfect-school.com.ua/uk/courses/
----
/WooCommerce Multilingual & Multicurrency with WPML plugin displays rating/
Thank you.

**Comment by senlin** [comment]
Hello Irina,

Thank you for your suggestion.

The difficulty with implementing translations of the ratings is that there are many different plugins that do ratings. If I manage to enable it for one rating plugin, I will also need to do so for others.

The GeoDirectory is a plugin that also uses ratings and although I have managed to sort of getting it working there, the next immediate issue is the structured SEO data, which I so far have not been able to make truly multilingual yet.

**Comment by Irinashl** [comment]
Hi Pieter,
thanks for the answer.
bad, I didn't want to use the WooCommerce Multilingual & Multicurrency with WPML plugin because it is very large and I do not need 98% of its functions.

And your Multilingual Comments WPML plugin is very small and requires no configuration.

**Comment by senlin** [comment]
The WooCommerce Multilingual & Multicurrency plugin is highly recommended when you have both WPML and WooCommerce installed on your site though. And my Multilingual Comments WPML plugin indeed is very small (thank you), but does something that the WooCommerce Multilingual & Multicurrency doesn't do.

**Comment by Irinashl** [comment]
I have WooCommerce installed, but I don't have: cart, currencies, prepayments, warehouse, etc.
I do not have a product, but offline training courses.
Your plugin combined ALL the reviews (which I needed) but no stars on the child page https://perfect-school.com.ua/uk/courses/

**Comment by senlin** [comment]
WooCommerce Reviews uses the default WP Comments functionality and that's why the combined number of reviews is showing correctly on either language.

The stars rating function is done differently and does not use the default WP Comments functionality and that is why the amount of stars does not come across.

In the future I might look into getting star ratings merged too for the translations, but not only is that very different functionality, the immediate issue that follows with that is the structured SEO data which does not come across.

Thanks for your understanding.

**Comment by Irinashl** [comment]
Great!
Good luck!
